
server.port=8082

# MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/auth_app
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: api.substring.com
    access-ttl-seconds: 3600
    refresh-ttl-seconds: 86400
    refresh-token-cookie-name: refreshToken
    cookie-secure: true
    cookie-http-only: true
    cookie-same-site: Lax